# Generated by Django 5.1.6 on 2025-03-15 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0024_remove_quizsubmissions_option_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizsubmission',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
