# Generated by Django 5.1.6 on 2025-03-15 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0025_quizsubmission_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizsubmission',
            name='question',
        ),
        migrations.RemoveField(
            model_name='quizsubmission',
            name='selected_option',
        ),
    ]
