# Generated by Django 5.1.6 on 2025-03-15 10:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0026_remove_quizsubmission_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizsubmission',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
